# propertyName(\ubcf4\ud638\uc790\uc6d0\uc758 URI)=propertyValue(\ubcf4\ud638\uc790\uc6d0\uc5d0 \ub300\ud55c \uc811\uadfc\uc744 \ud5c8\uc6a9\ud560 \uc5ed\ud560\ub4e4..)
# Map : in memory data (\ud718\ubc1c\uc131)
# Properties : .properties \ud30c\uc77c\uacfc \ub3d9\uae30\ud654 \ucc98\ub9ac\ub85c \ube44\ud718\ubc1c\uc131 \ub370\uc774\ud130\ub97c \uad00\ub9ac \ud560 \uc218 \uc788\uc74c.
#/mbti=ROLE_USER,ROLE_ADMIN
#/04/mediaList.jsp=ROLE_ADMIN\
/change-password=ROLE_USER,ROLE_ADMIN
/mypage=ROLE_USER,ROLE_ADMIN
/member/remove=ROLE_USER
/member/list=ROLE_ADMIN
/member/modify=ROLE_USER,ROLE_ADMIN